fix: bad eval of skip_large_bodies conf value resulting in always returning true
Kong/kong-plugin-liamp pull request #40
Opened 2020-10-02 21:59 UTC by ezrapagel

Fixes a regression introduced when attempting to just pass the `skip_large_bodies` setting, always evals to true

2020-10-04 15:55 UTC, Tieske requested changes
can you add some tests to prevent future regressions?

2020-10-05 06:31 UTC, Tieske commented
ping @hishamhm fyi for Kong 2.2

2020-10-05 15:22 UTC, ezrapagel commented
The existing test exercises the actual read function, and behaves as expected given the correct args. 
Maybe I'm missing something obvious, but I'm not sure how to add an access test just to verify that the conf setting was actually passed, given that the access suite has a mock implementation and won't hit the request util callsite.

2020-10-06 10:44 UTC, Tieske commented
sorry, my bad!

2020-10-06 10:44 UTC, merged